import inActiveCaseLoadAndUserHasSomeRolesFrom from '../inActiveCaseLoadAndUserHasSomeRolesFrom/InActiveCaseLoadAndUserHasSomeRolesFrom'

const inActiveCaseLoad = inActiveCaseLoadAndUserHasSomeRolesFrom([])

export default inActiveCaseLoad
